<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.0-windows;net8.0-windows</TargetFrameworks>
    <LangVersion>12.0</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Tewls.Shared\Tewls.Shared.csproj" />
  </ItemGroup>

</Project>
