<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFrameworks>net8.0-windows</TargetFrameworks>
		<LangVersion>12.0</LangVersion>
	</PropertyGroup>

	<ItemGroup>
	  <ProjectReference Include="..\TewlKit\TewlKit.csproj" />
	  <ProjectReference Include="..\Tewls.ZydisSharp\Tewls.ZydisSharp.csproj" />
	  <ProjectReference Include="..\Tewls\Tewls.csproj" />
	</ItemGroup>

</Project>